"""Generate tools/quickstart/mapexplore.lua for mGBA.

The script needs area and room NAMES, and those live in the decomp's
headers rather than in the ROM, so they are baked into the Lua at generation
time. Re-run this whenever roomid.h or area.h changes:

    python3 tools/quickstart/make_mapexplore_lua.py

Addresses are the linker's, read out of build/USA/tmc.map where they are not
already constants this harness uses.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import parse_tables as P

OUT = os.path.join(HERE, 'mapexplore.lua')

# (area id, room id) -> room name. Room ids are per-area, and a room's name
# always starts with its area's name, so the grouping is a prefix match -
# longest first, or ROOM_HYRULE_FIELD_* would be claimed by AREA_HYRULE.
area_by_name = dict(P.AREAS)
areas_longest = sorted(area_by_name, key=len, reverse=True)
rooms = {}
for rname, rid in P.ROOMS.items():
    for aname in areas_longest:
        if rname.startswith('ROOM_' + aname[len('AREA_'):] + '_'):
            # Strip the area prefix off the room name: the panel already
            # prints the area, so "HYRULE_FIELD / HYRULE_FIELD_SOUTH_..."
            # is just noise. A room whose name IS its area's keeps "MAIN".
            short = rname[len('ROOM_' + aname[len('AREA_'):] + '_'):]
            rooms.setdefault(area_by_name[aname], {})[rid] = short or 'MAIN'
            break

ITEMS = [
    ('sword',    0x01), ('green sword', 0x02), ('blue sword', 0x04),
    ('bombs',    0x07), ('remote bombs', 0x08), ('bow', 0x09), ('light arrow', 0x0a),
    ('boomerang', 0x0b), ('magic boomerang', 0x0c), ('shield', 0x0d), ('mirror shield', 0x0e),
    ('lantern',  0x0f), ('gust jar', 0x11), ('pacci cane', 0x12), ('mole mitts', 0x13),
    ('rocs cape', 0x14), ('pegasus boots', 0x15),
    ('grip ring', 0x44), ('bracelets', 0x45), ('flippers', 0x46),
]

with open(OUT, 'w') as f:
    f.write('-- GENERATED by tools/quickstart/make_mapexplore_lua.py - do not hand-edit.\n')
    f.write('-- Area and room names for the mGBA mapping overlay.\n')
    f.write('local M = {}\n\nM.areas = {\n')
    for aname, aid in sorted(P.AREAS.items(), key=lambda kv: kv[1]):
        f.write('  [%d] = "%s",\n' % (aid, aname[len('AREA_'):]))
    f.write('}\n\nM.rooms = {\n')
    for aid in sorted(rooms):
        f.write('  [%d] = {' % aid)
        f.write(', '.join('[%d]="%s"' % (rid, rn) for rid, rn in sorted(rooms[aid].items())))
        f.write('},\n')
    f.write('}\n\nM.items = {\n')
    for name, idx in ITEMS:
        f.write('  {"%s", %d},\n' % (name, idx))
    f.write('}\n\nNAMES = M\n\n')
    # The logic lives in mapexplore_body.lua so it stays readable and
    # editable as Lua; it is appended here so the file the user loads into
    # mGBA is self-contained (no require() from a script directory).
    with open(os.path.join(HERE, 'mapexplore_body.lua')) as body:
        f.write(body.read())

print('wrote %s: %d areas, %d rooms' % (OUT, len(P.AREAS), sum(len(v) for v in rooms.values())))
