-- GENERATED by tools/quickstart/make_mapexplore_lua.py - do not hand-edit.
-- Area and room names for the mGBA mapping overlay.
local M = {}

M.areas = {
  [0] = "MINISH_WOODS",
  [1] = "MINISH_VILLAGE",
  [2] = "HYRULE_TOWN",
  [3] = "HYRULE_FIELD",
  [4] = "CASTOR_WILDS",
  [5] = "RUINS",
  [6] = "MT_CRENEL",
  [7] = "CASTLE_GARDEN",
  [8] = "CLOUD_TOPS",
  [9] = "ROYAL_VALLEY",
  [10] = "VEIL_FALLS",
  [11] = "LAKE_HYLIA",
  [12] = "LAKE_WOODS_CAVE",
  [13] = "BEANSTALKS",
  [14] = "EMPTY",
  [15] = "HYRULE_DIG_CAVES",
  [16] = "MELARIS_MINE",
  [17] = "MINISH_PATHS",
  [18] = "CRENEL_MINISH_PATHS",
  [19] = "DIG_CAVES",
  [20] = "CRENEL_DIG_CAVE",
  [21] = "FESTIVAL_TOWN",
  [22] = "VEIL_FALLS_DIG_CAVE",
  [23] = "CASTOR_WILDS_DIG_CAVE",
  [24] = "OUTER_FORTRESS_OF_WINDS",
  [25] = "HYLIA_DIG_CAVES",
  [26] = "VEIL_FALLS_TOP",
  [27] = "NULL_1B",
  [28] = "NULL_1C",
  [29] = "NULL_1D",
  [30] = "NULL_1E",
  [31] = "NULL_1F",
  [32] = "MINISH_HOUSE_INTERIORS",
  [33] = "HOUSE_INTERIORS_1",
  [34] = "HOUSE_INTERIORS_2",
  [35] = "HOUSE_INTERIORS_3",
  [36] = "TREE_INTERIORS",
  [37] = "DOJOS",
  [38] = "CRENEL_CAVES",
  [39] = "MINISH_CRACKS",
  [40] = "HOUSE_INTERIORS_4",
  [41] = "GREAT_FAIRIES",
  [42] = "CASTOR_CAVES",
  [43] = "CASTOR_DARKNUT",
  [44] = "ARMOS_INTERIORS",
  [45] = "TOWN_MINISH_HOLES",
  [46] = "MINISH_RAFTERS",
  [47] = "GORON_CAVE",
  [48] = "WIND_TRIBE_TOWER",
  [49] = "WIND_TRIBE_TOWER_ROOF",
  [50] = "CAVES",
  [51] = "VEIL_FALLS_CAVES",
  [52] = "ROYAL_VALLEY_GRAVES",
  [53] = "MINISH_CAVES",
  [54] = "CASTLE_GARDEN_MINISH_HOLES",
  [55] = "37",
  [56] = "EZLO_CUTSCENE",
  [57] = "NULL_39",
  [58] = "NULL_3A",
  [59] = "NULL_3B",
  [60] = "NULL_3C",
  [61] = "NULL_3D",
  [62] = "NULL_3E",
  [63] = "NULL_3F",
  [64] = "40",
  [65] = "HYRULE_TOWN_UNDERGROUND",
  [66] = "GARDEN_FOUNTAINS",
  [67] = "HYRULE_CASTLE_CELLAR",
  [68] = "SIMONS_SIMULATION",
  [69] = "45",
  [70] = "NULL_46",
  [71] = "47",
  [72] = "DEEPWOOD_SHRINE",
  [73] = "DEEPWOOD_SHRINE_BOSS",
  [74] = "DEEPWOOD_SHRINE_ENTRY",
  [75] = "NULL_4B",
  [76] = "NULL_4C",
  [77] = "4D",
  [78] = "NULL_4E",
  [79] = "NULL_4F",
  [80] = "CAVE_OF_FLAMES",
  [81] = "CAVE_OF_FLAMES_BOSS",
  [82] = "NULL_52",
  [83] = "NULL_53",
  [84] = "NULL_54",
  [85] = "NULL_55",
  [86] = "NULL_56",
  [87] = "57",
  [88] = "FORTRESS_OF_WINDS",
  [89] = "FORTRESS_OF_WINDS_TOP",
  [90] = "INNER_MAZAAL",
  [91] = "NULL_5B",
  [92] = "NULL_5C",
  [93] = "NULL_5D",
  [94] = "NULL_5E",
  [95] = "5F",
  [96] = "TEMPLE_OF_DROPLETS",
  [97] = "NULL_61",
  [98] = "HYRULE_TOWN_MINISH_CAVES",
  [99] = "NULL_63",
  [100] = "NULL_64",
  [101] = "NULL_65",
  [102] = "NULL_66",
  [103] = "67",
  [104] = "ROYAL_CRYPT",
  [105] = "NULL_69",
  [106] = "NULL_6A",
  [107] = "NULL_6B",
  [108] = "NULL_6C",
  [109] = "NULL_6D",
  [110] = "NULL_6E",
  [111] = "6F",
  [112] = "PALACE_OF_WINDS",
  [113] = "PALACE_OF_WINDS_BOSS",
  [114] = "NULL_72",
  [115] = "NULL_73",
  [116] = "NULL_74",
  [117] = "NULL_75",
  [118] = "NULL_76",
  [119] = "77",
  [120] = "SANCTUARY",
  [121] = "NULL_79",
  [122] = "NULL_7A",
  [123] = "NULL_7B",
  [124] = "NULL_7C",
  [125] = "NULL_7D",
  [126] = "NULL_7E",
  [127] = "7F",
  [128] = "HYRULE_CASTLE",
  [129] = "SANCTUARY_ENTRANCE",
  [130] = "NULL_82",
  [131] = "NULL_83",
  [132] = "NULL_84",
  [133] = "NULL_85",
  [134] = "NULL_86",
  [135] = "87",
  [136] = "DARK_HYRULE_CASTLE",
  [137] = "DARK_HYRULE_CASTLE_OUTSIDE",
  [138] = "VAATIS_ARMS",
  [139] = "VAATI_3",
  [140] = "VAATI_2",
  [141] = "DARK_HYRULE_CASTLE_BRIDGE",
  [142] = "NULL_8E",
  [143] = "8F",
  [144] = "90",
  [145] = "91",
  [146] = "92",
  [147] = "93",
  [148] = "94",
  [149] = "95",
  [150] = "96",
  [151] = "97",
  [152] = "98",
}

M.rooms = {
  [0] = {[0]="MAIN"},
  [1] = {[0]="MAIN", [1]="SIDE_HOUSE_AREA", [2]="2", [3]="3"},
  [2] = {[0]="MAIN"},
  [3] = {[0]="WESTERN_WOODS_SOUTH", [1]="SOUTH_HYRULE_FIELD", [2]="EASTERN_HILLS_SOUTH", [3]="EASTERN_HILLS_CENTER", [4]="EASTERN_HILLS_NORTH", [5]="LON_LON_RANCH", [6]="NORTH_HYRULE_FIELD", [7]="TRILBY_HIGHLANDS", [8]="WESTERN_WOODS_NORTH", [9]="WESTERN_WOODS_CENTER"},
  [4] = {[0]="MAIN"},
  [5] = {[0]="ENTRANCE", [1]="BEANSTALK", [2]="TEKTITES", [3]="LADDER_TO_TEKTITES", [4]="FORTRESS_ENTRANCE", [5]="BELOW_FORTRESS_ENTRANCE"},
  [6] = {[0]="TOP", [1]="WALL_CLIMB", [2]="CAVERN_OF_FLAMES_ENTRANCE", [3]="CENTER", [4]="ENTRANCE"},
  [7] = {[0]="MAIN"},
  [8] = {[0]="CLOUD_TOPS", [1]="CLOUD_MIDDLES", [2]="CLOUD_BOTTOMS"},
  [9] = {[0]="MAIN", [1]="FOREST_MAZE"},
  [10] = {[0]="MAIN"},
  [11] = {[0]="MAIN", [1]="BEANSTALK"},
  [12] = {[0]="MAIN"},
  [13] = {[0]="CRENEL", [1]="LAKE_HYLIA", [2]="RUINS", [3]="EASTERN_HILLS", [4]="WESTERN_WOODS", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f", [16]="CRENEL_CLIMB", [17]="LAKE_HYLIA_CLIMB", [18]="RUINS_CLIMB", [19]="EASTERN_HILLS_CLIMB", [20]="WESTERN_WOODS_CLIMB"},
  [14] = {[0]="0"},
  [15] = {[0]="TOWN"},
  [16] = {[0]="MAIN"},
  [17] = {[0]="MINISH_VILLAGE", [1]="BOW", [2]="SCHOOLYARD", [3]="LON_LON_RANCH", [4]="LAKE_HYLIA"},
  [18] = {[0]="BEAN", [1]="SPRING_WATER", [2]="RAIN", [3]="MELARI"},
  [19] = {[0]="EASTERN_HILLS", [1]="1", [2]="2", [3]="TRILBY_HIGHLANDS"},
  [20] = {[0]="0"},
  [21] = {[0]="MAIN"},
  [22] = {[0]="0"},
  [23] = {[0]="0"},
  [24] = {[0]="ENTRANCE_HALL", [1]="2F", [2]="3F", [3]="MOLE_MITTS", [4]="SMALL_KEY"},
  [25] = {[0]="0", [1]="1"},
  [26] = {[0]="0"},
  [27] = {[0]="0"},
  [28] = {[0]="0"},
  [29] = {[0]="0"},
  [30] = {[0]="0"},
  [31] = {[0]="0"},
  [32] = {[0]="GENTARI_MAIN", [1]="GENTARI_EXIT", [2]="FESTARI", [3]="RED", [4]="GREEN", [5]="BLUE", [6]="SIDE_AREA", [7]="SHOE_MINISH", [8]="POT_MINISH", [9]="BARREL_MINISH", [10]="NULL1", [11]="NULL2", [12]="c", [13]="d", [14]="e", [15]="f", [16]="MELARI_MINES_SOUTHWEST", [17]="MELARI_MINES_SOUTHEAST", [18]="MELARI_MINES_EAST", [19]="13", [20]="14", [21]="15", [22]="16", [23]="17", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f", [32]="HYRULE_FIELD_SOUTHWEST", [33]="SOUTH_HYRULE_FIELD", [34]="NEXT_TO_KNUCKLE", [35]="LIBRARI", [36]="HYRULE_FIELD_EXIT", [37]="HYRULE_TOWN", [38]="MINISH_WOODS_BOMB", [39]="LAKE_HYLIA_OCARINA"},
  [33] = {[0]="MAYOR", [1]="POST_OFFICE", [2]="LIBRARY_2F", [3]="LIBRARY_1F", [4]="INN_1F", [5]="INN_WEST_ROOM", [6]="INN_MIDDLE_ROOM", [7]="INN_EAST_ROOM", [8]="INN_WEST_2F", [9]="INN_EAST_2F", [10]="INN_MINISH_HEART_PIECE", [11]="SCHOOL_WEST", [12]="SCHOOL_EAST", [13]="d", [14]="e", [15]="f", [16]="10", [17]="11", [18]="12", [19]="13", [20]="14", [21]="15", [22]="16", [23]="17", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f"},
  [34] = {[0]="STRANGER", [1]="WEST_ORACLE", [2]="2", [3]="3", [4]="DR_LEFT", [5]="5", [6]="ROMIO", [7]="JULIETTA", [8]="PERCY", [9]="EAST_ORACLE", [10]="a", [11]="b", [12]="CUCCO", [13]="d", [14]="e", [15]="f", [16]="LINKS_HOUSE_ENTRANCE", [17]="LINKS_HOUSE_SMITH", [18]="DAMPE", [19]="13", [20]="STOCKWELL_LAKE_HOUSE", [21]="LINKS_HOUSE_BEDROOM", [22]="16", [23]="17", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f", [32]="20", [33]="21", [34]="22", [35]="23", [36]="24", [37]="25", [38]="26", [39]="27", [40]="28", [41]="29", [42]="2a", [43]="2b", [44]="2c", [45]="2d", [46]="2e", [47]="2f"},
  [35] = {[0]="STOCKWELL_SHOP", [1]="CAFE", [2]="REM_SHOE_SHOP", [3]="BAKERY", [4]="SIMON", [5]="FIGURINE_HOUSE", [6]="BORLOV_ENTRANCE", [7]="CARLOV", [8]="BORLOV", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f"},
  [36] = {[0]="WITCH_HUT", [1]="1", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f", [16]="STAIRS_TO_CARLOV", [17]="PERCYS_TREEHOUSE", [18]="SOUTH_HYRULE_FIELD_HEART_PIECE", [19]="WAVEBLADE", [20]="14", [21]="BOOMERANG_NORTHWEST", [22]="BOOMERANG_NORTHEAST", [23]="BOOMERANG_SOUTHWEST", [24]="BOOMERANG_SOUTHEAST", [25]="WESTERN_WOODS_HEART_PIECE", [26]="NORTH_HYRULE_FIELD_FAIRY_FOUNTAIN", [27]="MINISH_WOODS_GREAT_FAIRY", [28]="1c", [29]="MINISH_WOODS_BUSINESS_SCRUB", [30]="1e", [31]="UNUSED_HEART_CONTAINER"},
  [37] = {[0]="GRAYBLADE", [1]="SPLITBLADE", [2]="GREATBLADE", [3]="SCARBLADE", [4]="SWIFTBLADE_I", [5]="GRIMBLADE", [6]="WAVEBLADE", [7]="7", [8]="8", [9]="9", [10]="TO_GRIMBLADE", [11]="TO_SPLITBLADE", [12]="TO_GREATBLADE", [13]="TO_SCARBLADE", [14]="e", [15]="f"},
  [38] = {[0]="BLOCK_PUSHING", [1]="PILLAR_CAVE", [2]="BRIDGE_SWITCH", [3]="EXIT_TO_MINES", [4]="GRIP_RING", [5]="FAIRY_FOUNTAIN", [6]="SPINY_CHU_PUZZLE", [7]="CHUCHU_POT_CHEST", [8]="WATER_HEART_PIECE", [9]="RUPEE_FAIRY_FOUINTAIN", [10]="HELMASAUR_HALLWAY", [11]="MUSHROOM_KEESE", [12]="LADDER_TO_SPRING_WATER", [13]="BOMB_BUSINESS_SCRUB", [14]="HERMIT", [15]="HINT_SCRUB", [16]="TO_GRAYBLADE"},
  [39] = {[0]="LON_LON_RANCH_NORTH", [1]="LAKE_HYLIA_EAST", [2]="HYRULE_CASTLE_GARDEN", [3]="MT_CRENEL", [4]="EAST_HYRULE_CASTLE", [5]="5", [6]="CASTOR_WILDS_BOW", [7]="RUINS_ENTRANCE", [8]="MINISH_WOODS_SOUTH", [9]="CASTOR_WILDS_NORTH", [10]="CASTOR_WILDS_WEST", [11]="CASTOR_WILDS_MIDDLE", [12]="RUINS_TEKTITE", [13]="CASTOR_WILDS_NEXT_TO_BOW", [14]="e", [15]="f", [16]="10", [17]="11", [18]="12", [19]="13", [20]="14", [21]="15", [22]="16", [23]="17"},
  [40] = {[0]="CARPENTER", [1]="SWIFTBLADE", [2]="RANCH_HOUSE_WEST", [3]="RANCH_HOUSE_EAST", [4]="FARM_HOUSE", [5]="MAYOR_LAKE_CABIN", [6]="6", [7]="7", [8]="8", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f"},
  [41] = {[0]="GRAVEYARD", [1]="MINISH_WOODS", [2]="CRENEL", [3]="NOT_IMPLEMENTED"},
  [42] = {[0]="SOUTH", [1]="NORTH", [2]="WIND_RUINS", [3]="DARKNUT", [4]="HEART_PIECE", [5]="5", [6]="6", [7]="7"},
  [43] = {[0]="MAIN", [1]="HALL"},
  [44] = {[0]="RUINS_ENTRANCE_NORTH", [1]="RUINS_ENTRANCE_SOUTH", [2]="RUINS_LEFT", [3]="RUINS_MIDDLE_LEFT", [4]="RUINS_MIDDLE_RIGHT", [5]="RUINS_RIGHT", [6]="6", [7]="RUINS_GRASS_PATH", [8]="8", [9]="FORTRESS_LEFT", [10]="FORTRESS_RIGHT"},
  [45] = {[0]="MAYORS_HOUSE", [1]="WEST_ORACLE", [2]="DR_LEFT", [3]="CARPENTER", [4]="CAFE", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f", [16]="LIBRARY_BOOKSHELF", [17]="LIBRARY_BOOKS_HOUSE", [18]="REM_SHOE_SHOP", [19]="13"},
  [46] = {[0]="CAFE", [1]="STOCKWELL", [2]="DR_LEFT", [3]="BAKERY"},
  [47] = {[0]="STAIRS", [1]="MAIN"},
  [48] = {[0]="ENTRANCE", [1]="FLOOR_1", [2]="FLOOR_2", [3]="FLOOR_3"},
  [49] = {[0]="0"},
  [50] = {[0]="BOOMERANG", [1]="TO_GRAVEYARD", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="TRILBY_KEESE_CHEST", [8]="TRILBY_FAIRY_FOUNTAIN", [9]="SOUTH_HYRULE_FIELD_FAIRY_FOUNTAIN", [10]="a", [11]="HYRULE_TOWN_WATERFALL", [12]="LON_LON_RANCH", [13]="LON_LON_RANCH_SECRET", [14]="TRILBY_HIGHLANDS", [15]="LON_LON_RANCH_WALLET", [16]="SOUTH_HYRULE_FIELD_RUPEE", [17]="TRILBY_RUPEE", [18]="TRILBY_MITTS_FAIRY_FOUNTAIN", [19]="HILLS_KEESE_CHEST", [20]="BOTTLE_BUSINESS_SCRUB", [21]="HEART_PIECE_HALLWAY", [22]="NORTH_HYRULE_FIELD_FAIRY_FOUNTAIN", [23]="KINSTONE_BUSINESS_SCRUB"},
  [51] = {[0]="HALLWAY_2F", [1]="HALLWAY_1F", [2]="HALLWAY_SECRET_ROOM", [3]="ENTRANCE", [4]="EXIT", [5]="SECRET_CHEST", [6]="HALLWAY_SECRET_STAIRCASE", [7]="HALLWAY_BLOCK_PUZZLE", [8]="HALLWAY_RUPEE_PATH", [9]="HALLWAY_HEART_PIECE", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f"},
  [52] = {[0]="HEART_PIECE", [1]="GINA"},
  [53] = {[0]="BEAN_PESTO", [1]="SOUTHEAST_WATER_1", [2]="2", [3]="RUINS", [4]="OUTSIDE_LINKS_HOUSE", [5]="MINISH_WOODS_NORTH_1", [6]="6", [7]="LAKE_HYLIA_NORTH", [8]="LAKE_HYLIA_LIBRARI", [9]="MINISH_WOODS_SOUTHWEST"},
  [54] = {[0]="0", [1]="1"},
  [55] = {[0]="0", [1]="1"},
  [56] = {[0]="0"},
  [57] = {[0]="0"},
  [58] = {[0]="0"},
  [59] = {[0]="0"},
  [60] = {[0]="0"},
  [61] = {[0]="0"},
  [62] = {[0]="0"},
  [63] = {[0]="0"},
  [64] = {[0]="0"},
  [65] = {[0]="0", [1]="1"},
  [66] = {[0]="EAST", [1]="WEST"},
  [67] = {[0]="0", [1]="1"},
  [68] = {[0]="0"},
  [69] = {[0]="0"},
  [70] = {[0]="0"},
  [71] = {[0]="0"},
  [72] = {[0]="MADDERPILLAR", [1]="BLUE_PORTAL", [2]="STAIRS_TO_B1", [3]="POT_BRIDGE", [4]="DOUBLE_STATUE", [5]="MAP", [6]="BARREL", [7]="BUTTON", [8]="MULLDOZER", [9]="PILLARS", [10]="LEVER", [11]="ENTRANCE", [12]="c", [13]="d", [14]="e", [15]="f", [16]="TORCHES", [18]="COMPASS", [19]="13", [20]="LILY_PAD_WEST", [21]="LILY_PAD_EAST", [22]="16", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f", [32]="INSIDE_BARREL"},
  [73] = {[0]="MAIN", [17]="KEY", [23]="DOOR"},
  [74] = {[0]="MAIN"},
  [75] = {[0]="0"},
  [76] = {[0]="0"},
  [77] = {[0]="0"},
  [78] = {[0]="0"},
  [79] = {[0]="0"},
  [80] = {[0]="AFTER_CANE", [1]="SPINY_CHU", [2]="CART_TO_SPINY_CHU", [3]="ENTRANCE", [4]="MAIN_CART", [5]="NORTH_ENTRANCE", [6]="CART_WEST", [7]="HELMASAUR_FIGHT", [8]="ROLLOBITE_LAVA_ROOM", [9]="MINISH_LAVA_ROOM", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f", [16]="MINISH_SPIKES", [17]="TOMPAS_DOOM", [18]="BEFORE_GLEEROK", [19]="BOSSKEY_PATH1", [20]="BOSSKEY_PATH2", [21]="COMPASS", [22]="BOB_OMB_WALL", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f", [32]="20"},
  [81] = {[0]="0", [23]="DOOR"},
  [82] = {[0]="0"},
  [83] = {[0]="0"},
  [84] = {[0]="0"},
  [85] = {[0]="0"},
  [86] = {[0]="0"},
  [87] = {[0]="0"},
  [88] = {[0]="DOUBLE_EYEGORE", [1]="BEFORE_MAZAAL", [2]="EAST_KEY_LEVER", [3]="PIT_PLATFORMS", [4]="WEST_KEY_LEVER", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9", [10]="a", [11]="b", [12]="c", [13]="d", [14]="e", [15]="f", [16]="DARKNUT_ROOM", [17]="ARROW_EYE_BRIDGE", [18]="NORTH_SPLIT_PATH_PIT", [19]="WALLMASTER_MINISH_PORTAL", [20]="PILLAR_CLONE_BUTTONS", [21]="ROTATING_SPIKE_TRAPS", [22]="MAZAAL", [23]="STALFOS", [24]="ENTRANCE_MOLE_MITTS", [25]="MAIN_2F", [26]="MINISH_HOLE", [27]="BOSS_KEY", [28]="WEST_STAIRS_2F", [29]="EAST_STAIRS_2F", [30]="1e", [31]="1f", [32]="WEST_STAIRS_1F", [33]="CENTER_STAIRS_1F", [34]="EAST_STAIRS_1F", [35]="WIZZROBE", [36]="HEART_PIECE", [37]="25", [38]="26", [39]="27"},
  [89] = {[0]="MAIN"},
  [90] = {[0]="MAIN", [1]="PHASE_1"},
  [91] = {[0]="0"},
  [92] = {[0]="0"},
  [93] = {[0]="0"},
  [94] = {[0]="0"},
  [95] = {[0]="0"},
  [96] = {[0]="WEST_HOLE", [1]="NORTH_SPLIT_ROOM", [2]="EAST_HOLE", [3]="ENTRANCE", [4]="NORTHWEST_STAIRS", [5]="SCISSORS_MINIBOSS", [6]="WATERFALL_NORTHWEST", [7]="WATERFALL_NORTHEAST", [8]="ELEMENT", [9]="ICE_CORNER", [10]="ICE_PIT_MAZE", [11]="HOLE_TO_BLUE_CHU_KEY", [12]="WEST_WATERFALL_SOUTHEAST", [13]="WEST_WATERFALL_SOUTHWEST", [14]="BIG_OCTO", [15]="TO_BLUE_CHU", [16]="BLUE_CHU", [17]="BLUE_CHU_KEY", [18]="12", [19]="13", [20]="14", [21]="15", [22]="16", [23]="17", [24]="18", [25]="19", [26]="1a", [27]="1b", [28]="1c", [29]="1d", [30]="1e", [31]="1f", [32]="BOSS_KEY", [33]="NORTH_SMALL_KEY", [34]="BLOCK_CLONE_BUTTON_PUZZLE", [35]="BLOCK_CLONE_PUZZLE", [36]="BLOCK_CLONE_ICE_BRIDGE", [37]="STAIRS_TO_SCISSORS_MINIBOSS", [38]="SPIKE_BAR_FLIPPER_ROOM", [39]="9_LANTERNS", [40]="LILYPAD_ICE_BLOCKS", [41]="29", [42]="MULLDOZERS_FIRE_BARS", [43]="DARK_MAZE", [44]="TWIN_MADDERPILLARS", [45]="AFTER_TWIN_MADDERPILLARS", [46]="BLUE_CHU_KEY_LEVER", [47]="MULLDOZER_KEY", [48]="BEFORE_TWIN_MADDERPILLARS", [49]="LILYPAD_B2_WEST", [50]="COMPASS", [51]="DARK_SCISSOR_BEETLES", [52]="LILYPAD_B2_MIDDLE", [53]="ICE_MADDERPILLAR", [54]="FLAMEBAR_BLOCK_PUZZLE", [55]="37", [56]="38", [57]="39", [58]="3a", [59]="3b", [60]="3c", [61]="3d", [62]="3e", [63]="3f"},
  [97] = {[0]="0"},
  [98] = {[0]="0"},
  [99] = {[0]="0"},
  [100] = {[0]="0"},
  [101] = {[0]="0"},
  [102] = {[0]="0"},
  [103] = {[0]="0"},
  [104] = {[0]="0", [1]="WATER_ROPE", [2]="GIBDO", [3]="3", [4]="KEY_BLOCK", [5]="5", [6]="6", [7]="MUSHROOM_PIT", [8]="ENTRANCE"},
  [105] = {[0]="0"},
  [106] = {[0]="0"},
  [107] = {[0]="0"},
  [108] = {[0]="0"},
  [109] = {[0]="0"},
  [110] = {[0]="0"},
  [111] = {[0]="0"},
  [112] = {[0]="GYORG_TORNADO", [2]="BEFORE_BALL_AND_CHAIN_SOLDIERS", [3]="GYORG_BOSS_DOOR", [4]="EAST_CHEST_FROM_GYORG_BOSS_DOOR", [5]="MOBLIN_AND_WIZZROBE_FIGHT", [6]="FOUR_BUTTON_STALFOS", [7]="FAN_AND_KEY_TO_BOSS_KEY", [8]="BALL_AND_CHAIN_SOLDIERS", [9]="BOMBAROSSA_PATH", [10]="HOLE_TO_DARKNUT", [11]="TO_BOMBAROSSA_PATH", [12]="DARKNUT_MINIBOSS", [13]="BOMB_WALL_INSIDE", [14]="BOMB_WALL_OUTSIDE", [15]="CLOUD_JUMPS", [16]="BLOCK_MAZE_TO_BOSS_DOOR", [17]="CRACKED_FLOOR_LAKITU", [18]="HEART_PIECE_BRIDGE", [19]="FAN_BRIDGE", [20]="TO_FAN_BRIDGE", [21]="RED_WARP_HALL", [22]="PLATFORM_CLONE_RIDE", [23]="PIT_CORNER_AFTER_KEY", [24]="PLATFORM_CROW_RIDE", [25]="GRATE_PLATFORM_RIDE", [26]="POT_PUSH", [27]="FLOORMASTER_LEVER", [28]="MAP", [29]="CORNER_TO_MAP", [30]="STAIRS_AFTER_FLOORMASTER", [31]="HOLE_TO_KINSTONE_WIZZROBE", [32]="KEY_ARROW_BUTTON", [33]="GRATES_TO_3F", [34]="SPINY_FIGHT", [35]="PEAHAT_SWITCH", [36]="WHIRLWIND_BOMBAROSSA", [37]="DOOR_TO_STALFOS_FIREBAR", [38]="STALFOS_FIREBAR_HOLE", [39]="SHORTCUT_DOOR_BUTTONS", [40]="TO_PEAHAT_SWITCH", [41]="KINSTONE_WIZZROBE_FIGHT", [42]="GIBDO_STAIRS", [43]="SPIKE_BAR_SMALL_KEY", [44]="ROC_CAPE", [45]="FIRE_BAR_GRATES", [46]="PLATFORM_RIDE_BOMBAROSSAS", [47]="BRIDGE_AFTER_DARKNUT", [48]="BRIDGE_SWITCHES_CLONE_BLOCK", [49]="ENTRANCE_ROOM", [50]="DARK_COMPASS_HALL", [51]="33"},
  [113] = {[0]="0", [1]="KEY"},
  [114] = {[0]="0"},
  [115] = {[0]="0"},
  [116] = {[0]="0"},
  [117] = {[0]="0"},
  [118] = {[0]="0"},
  [119] = {[0]="0"},
  [120] = {[0]="HALL", [1]="MAIN", [2]="STAINED_GLASS"},
  [121] = {[0]="0"},
  [122] = {[0]="0"},
  [123] = {[0]="0"},
  [124] = {[0]="0"},
  [125] = {[0]="0"},
  [126] = {[0]="0"},
  [127] = {[0]="0"},
  [128] = {[0]="0", [1]="1", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="7"},
  [129] = {[0]="MAIN"},
  [130] = {[0]="0"},
  [131] = {[0]="0"},
  [132] = {[0]="0"},
  [133] = {[0]="0"},
  [134] = {[0]="0"},
  [135] = {[0]="0"},
  [136] = {[0]="1F_ENTRANCE", [1]="3F_TOP_LEFT_TOWER", [2]="3F_TOP_RIGHT_TOWER", [3]="3F_BOTTOM_LEFT_TOWER", [4]="3F_BOTTOM_RIGHT_TOWER", [5]="3F_KEATON_HALL_TO_VAATI", [6]="3F_TRIPLE_DARKNUT", [7]="2F_TOP_LEFT_TOWER", [8]="2F_TOP_LEFT_CORNER", [9]="2F_BOSS_KEY", [10]="2F_BLUE_WARP", [11]="2F_TOP_RIGHT_CORNER_GHINI", [12]="2F_TOP_RIGHT_CORNER_TORCHES", [13]="2F_TOP_RIGHT_TOWER", [14]="2F_TOP_LEFT_DARKNUT", [15]="2F_SPARKS", [16]="2F_TOP_RIGHT_DARKNUTS", [17]="2F_LEFT", [18]="2F_RIGHT", [19]="2F_BOTTOM_LEFT_DARKNUTS", [20]="2F_BOSS_DOOR", [21]="2F_BOTTOM_RIGHT_DARKNUT", [22]="2F_BOTTOM_LEFT_CORNER_PUZZLE", [23]="2F_ENTRANCE", [24]="2F_BOTTOM_RIGHT_CORNER", [25]="2F_BOTTOM_LEFT_TOWER", [26]="2F_BOTTOM_LEFT_GHINI", [27]="1b", [28]="B1_ENTRANCE", [29]="2F_BOTTOM_RIGHT_TOWER", [30]="1F_TOP_LEFT_TOWER", [31]="1F_THRONE_ROOM", [32]="1F_COMPASS", [33]="1F_TOP_RIGHT_TOWER", [34]="1F_BEFORE_THRONE", [35]="1F_LOOP_TOP_LEFT", [36]="1F_LOOP_TOP", [37]="1F_LOOP_TOP_RIGHT", [38]="1F_LOOP_LEFT", [39]="1F_LOOP_RIGHT", [40]="1F_LOOP_BOTTOM_LEFT", [41]="1F_LOOP_BOTTOM", [42]="1F_LOOP_BOTTOM_RIGHT", [43]="1F_BOTTOM_LEFT_TOWER", [44]="1F_BOTTOM_RIGHT_TOWER", [45]="B1_BELOW_THRONE", [46]="B1_BELOW_COMPASS", [47]="B1_BEFORE_THRONE", [48]="B1_TO_PRISON", [49]="B1_BOMB_WALL", [50]="B1_KEATONS", [51]="B1_TO_PRISON_FIREBAR", [52]="B1_CANNONS", [53]="B1_LEFT", [54]="B1_RIGHT", [55]="B1_MAP", [56]="B2_TO_PRISON", [57]="B2_PRISON", [58]="B2_DROPDOWN", [59]="3b", [60]="3c", [61]="3d", [62]="3e", [63]="3f"},
  [137] = {[0]="ZELDA_STATUE_PLATFORM", [1]="GARDEN", [2]="NORTHWEST", [3]="NORTHEAST", [4]="EAST", [5]="SOUTHWEST", [6]="SOUTH", [7]="SOUTHEAST"},
  [138] = {[0]="FIRST", [1]="SECOND"},
  [139] = {[0]="0"},
  [140] = {[0]="0"},
  [141] = {[0]="MAIN"},
  [142] = {[0]="0"},
  [143] = {[0]="0"},
}

M.items = {
  {"sword", 1},
  {"green sword", 2},
  {"blue sword", 4},
  {"bombs", 7},
  {"remote bombs", 8},
  {"bow", 9},
  {"light arrow", 10},
  {"boomerang", 11},
  {"magic boomerang", 12},
  {"shield", 13},
  {"mirror shield", 14},
  {"lantern", 15},
  {"gust jar", 17},
  {"pacci cane", 18},
  {"mole mitts", 19},
  {"rocs cape", 20},
  {"pegasus boots", 21},
  {"grip ring", 68},
  {"bracelets", 69},
  {"flippers", 70},
}

NAMES = M

-- ---------------------------------------------------------------------------
-- The Minish Cap map explorer, for mGBA's Lua console.
--
-- Load it with the mapexplore ROM running:  Tools > Scripting > Load script
--
-- It gives you three things while you walk:
--
--   * a LIVE PANEL with the room you are in, where you are in it, and the
--     tile you are standing on;
--   * a ROOM CHANGE line in the log every time you cross a door, seam or
--     border - which is the edge list of the world graph, written as you
--     walk it;
--   * a WAYPOINT line on L+R, for pinning a spot you want to come back to.
--
-- The tile line is the one that matters most for the reachability model.
-- "coll" is the collision byte, "type" the tileType the tileset maps that
-- tile index to, and "act" the actTile - the triple the engine itself keys
-- on, and the same triple tools/quickstart/tileclass.py counts. When you
-- find a square that needs an item, note its triple: the requirement is a
-- property of the CLASS, so recording it once teaches the model every tile
-- of that kind in the game.
-- ---------------------------------------------------------------------------

local RC = 0x03000bf0          -- gRoomControls
local PLAYER = 0x03001160      -- gPlayerEntity
local MAP_BOTTOM = 0x02025eb0  -- gMapBottom
local MAP_TOP = 0x0200b650     -- gMapTop
local SAVE = 0x02002a40        -- gSave
local INV = SAVE + 0xF2        -- gSave.inventory, 2 bits per item

local KEY_L, KEY_R = 512, 256

local function rd8(a) return emu:read8(a) end
local function rd16(a) return emu:read16(a) end

local function areaName(a)
  return NAMES.areas[a] or string.format("AREA_%d", a)
end

local function roomName(a, r)
  local t = NAMES.rooms[a]
  return (t and t[r]) or string.format("ROOM_%d", r)
end

-- The engine's own tile triple for one room-local tile position.
local function tileClass(base, tx, ty)
  local pos = tx + ty * 64
  local idx = rd16(base + 0x0004 + pos * 2) % 0x400
  return rd8(base + 0x2004 + pos),                 -- collisionData
         rd16(base + 0x5004 + idx * 2),            -- tileTypes[tileIndex]
         rd8(base + 0xb004 + pos)                  -- actTiles
end

local function state()
  local s = {}
  s.area, s.room = rd8(RC + 4), rd8(RC + 5)
  s.ox, s.oy = rd16(RC + 6), rd16(RC + 8)
  s.w, s.h = rd16(RC + 0x1e), rd16(RC + 0x20)
  s.wx, s.wy = rd16(PLAYER + 0x2e), rd16(PLAYER + 0x32)
  s.layer = rd8(PLAYER + 0x38)
  s.lx, s.ly = s.wx - s.ox, s.wy - s.oy
  s.tx, s.ty = s.lx // 16, s.ly // 16
  s.base = (s.layer == 2) and MAP_TOP or MAP_BOTTOM
  if s.tx >= 0 and s.ty >= 0 and s.tx < 64 and s.ty < 64 then
    s.col, s.typ, s.act = tileClass(s.base, s.tx, s.ty)
  else
    s.col, s.typ, s.act = -1, -1, -1
  end
  return s
end

local function held()
  local out = {}
  for _, it in ipairs(NAMES.items) do
    local name, idx = it[1], it[2]
    local byte = rd8(INV + (idx // 4))
    if ((byte >> ((idx % 4) * 2)) & 3) ~= 0 then
      out[#out + 1] = name
    end
  end
  return out
end

local function where(s)
  return string.format("%s / %s", areaName(s.area), roomName(s.area, s.room))
end

local function tileLine(s)
  if s.col < 0 then
    return "tile        (off the map)"
  end
  return string.format("tile class  coll 0x%02x  type 0x%04x  act 0x%02x", s.col, s.typ, s.act)
end

-- A neighbour's collision, for reading what is blocking you right now.
local function neighbours(s)
  local function at(dx, dy)
    local tx, ty = s.tx + dx, s.ty + dy
    if tx < 0 or ty < 0 or tx >= 64 or ty >= 64 then return -1 end
    return rd8(s.base + 0x2004 + tx + ty * 64)
  end
  return string.format("around      N 0x%02x  S 0x%02x  W 0x%02x  E 0x%02x",
                       at(0, -1) % 256, at(0, 1) % 256, at(-1, 0) % 256, at(1, 0) % 256)
end

-- The buffer is optional: not every mGBA build exposes createBuffer, and
-- on the ones that do not, even ASKING for the field can raise. Everything
-- important goes to console:log anyway, so a missing panel costs nothing.
local buffer = nil
do
  local ok, b = pcall(function() return console:createBuffer("map explorer") end)
  if ok and b then
    buffer = b
    pcall(function() buffer:setSize(64, 14) end)
  end
end

local function paint(s)
  if not buffer then return end
  buffer:clear()
  buffer:print(string.format("%s\n", where(s)))
  buffer:print(string.format("area %d  room %d  layer %d\n", s.area, s.room, s.layer))
  buffer:print(string.format("room        %dx%d px  (%dx%d tiles)  origin (%d,%d)\n",
                             s.w, s.h, s.w // 16, s.h // 16, s.ox, s.oy))
  buffer:print(string.format("player      world (%d,%d)  local (%d,%d)  tile (%d,%d)\n",
                             s.wx, s.wy, s.lx, s.ly, s.tx, s.ty))
  buffer:print(tileLine(s) .. "\n")
  buffer:print(neighbours(s) .. "\n")
  buffer:print("items       " .. table.concat(held(), " ") .. "\n")
  buffer:print("\nL+R logs a waypoint.\n")
end

-- A line you can paste straight into the model: where you are, in the
-- coordinates the tables use, plus the tile class under your feet.
local function stamp(tag, s)
  return string.format("%-9s %s  local (%d,%d)  tile (%d,%d)  layer %d  coll 0x%02x type 0x%04x act 0x%02x",
                       tag, where(s), s.lx, s.ly, s.tx, s.ty, s.layer,
                       s.col % 256, s.typ % 0x10000, s.act % 256)
end

local lastArea, lastRoom = -1, -1
local lastWhere = nil
local waypointHeld = false
local frames = 0

local function onFrame()
  frames = frames + 1
  local s = state()

  if s.area ~= lastArea or s.room ~= lastRoom then
    -- Wait for the room to settle before reporting: mid-transition the
    -- origin has not been rewritten yet, so the local coordinates on the
    -- first frames of a new room are the OLD room's arithmetic.
    if s.w > 0 then
      if lastWhere then
        console:log(string.format("ROOM %s  ->  %s", lastWhere, where(s)))
      else
        console:log(string.format("START     %s", where(s)))
      end
      console:log("  " .. stamp("arrive", s))
      lastArea, lastRoom, lastWhere = s.area, s.room, where(s)
    end
  end

  local keys = emu:getKeys()
  local both = (keys & KEY_L) ~= 0 and (keys & KEY_R) ~= 0
  if both and not waypointHeld then
    console:log(stamp("WAYPOINT", s))
    console:log("  items: " .. table.concat(held(), " "))
  end
  waypointHeld = both

  if frames % 4 == 0 then paint(s) end
end

callbacks:add("frame", onFrame)
console:log("map explorer loaded - walk around; room changes log themselves, L+R pins a waypoint")
